name: Deployment Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-ecr:
    name: Build Docker Image and Push to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-ec2:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy to EC2 instance
        run: |
          instance_ids=("i-0e92c3c4a3db73007" "i-0029335c18d9eb9bf")
          command_id=$(aws ssm send-command \
            --instance-ids "${instance-ids[@]}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker image from ECR" \
            --parameters 'commands=["aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
              "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ steps.login-ecr.outputs.ECR_REPOSITORY }}/:${{ steps.login-ecr.outputs.IMAGE_TAG }}",
              "docker run --rm -d -p 3000:3000 ${{ steps.login-ecr.outputs.registry }}/${{ steps.login-ecr.outputs.ECR_REPOSITORY }}/:${{ steps.login-ecr.outputs.IMAGE_TAG }}"
            ]' --query "Command.CommandId" --output text)

          echo "SSM CommandId: $command_id"

          for id in "${instance_ids[@]}"; do
            aws ssm wait command-executed \
              --command-id $command_id \
              --instance-id $id || true
          done
